apiVersion: v1
kind: Service
metadata:
  name: kubernetes-tutorial-cluster-ip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 30080
  selector:
    app: kubernetes-tutorial-deployment
  type: NodePort
